apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ey1u5pown-go
  janus-idp.io/tekton: ey1u5pown-go
  backstage.io/kubernetes-id: ey1u5pown-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ey1u5pown-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
