apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ey1u5pown-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ey1u5pown-go 
  name: ey1u5pown-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ey1u5pown-go 
